apiVersion: v1
kind: ConfigMap
metadata:
  name: pgconfig
  labels:
    app: postgres
data:
  POSTGRES_DB: pgdb
  POSTGRES_USER: user
  POSTGRES_PASSWORD: secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.1
          envFrom:
            - configMapRef:
                name: pgconfig
          ports:
            - containerPort: 5432
              name: pgdb
          volumeMounts:
            - name: pgdb
              mountPath: /var/lib/postgresql/data/
              subPath: postgres
      volumes:
        - name: pgdb
          persistentVolumeClaim:
            claimName: psql-pv-claim
