apiVersion: v1
kind: ConfigMap
metadata:
  name: pgconfig
  labels:
    app: postgres
data:
  POSTGRES_DB: pgdb
  POSTGRES_USER: user
  POSTGRES_PASSWORD: secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: pgservice
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgstateful
spec:
  serviceName: "postgres-headless"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: pgconfig
          ports:
            - containerPort: 5432
              name: pgdb
          volumeMounts:
            - name: pgdb
              mountPath: /var/lib/postgresql/data/
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: pgdb
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 3Gi
